version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
  pre_build:
    commands:
       - echo Entered the pre_build phase...
       - sed -i 's/localhost:8080/capstone-elb-1089695435.us-east-1.elb.amazonaws.com/g' src/main/resources/static/index.html
      # - command
  build:
    commands:
       - echo Entered the build phase...
       - echo Build started on `date`
       - mvn package
      # - command
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
     - target/webserver-0.0.1-SNAPSHOT.jar
     - appspec.yml
     - scripts/*
  discard-paths: yes
#base-directory: location