package com.homeautomation.webserver.user;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

/*
 * Description: The User class is the main model for our devices. The id is automatically generated by MongoDB in the
 * storage process. The variables username and password are set by the client.
 */

@Document(collection = "users")
public class ApplicationUser {

    @Id
    private String id;
    private String username;
    private String password;

    public String getUsername(){
        return username;
    }

    public void setName(String username){
        this.username = username;
    }

    public String getPassword(){
        return password;
    }

    public void setPassword(String password){
        this.password = password;
    }

    public String getId(){
        return id;
    }
}
